name: Bulk ingest monthly CH accounts → Azure SQL

on:
  workflow_dispatch:
    inputs:
      YEAR:
        description: "Year (e.g., 2024) — or leave blank to use range"
        required: false
        default: ""
      START:
        description: "Start (YYYY-MM)"
        required: false
        default: ""
      END:
        description: "End (YYYY-MM)"
        required: false
        default: ""

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    env:
      AZURE_SQL_SERVER:   ${{ secrets.AZURE_SQL_SERVER }}
      AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
      AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
      AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
      AZURE_SQL_CONN:     ${{ secrets.AZURE_SQL_CONN }}

    steps:
      - uses: actions/checkout@v4

      - name: Python + ODBC
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install ODBC driver & deps
        run: |
          sudo su -c 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
          sudo su -c 'curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list'
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ingest (choose year or start/end)
        run: |
          if [ -n "${{ github.event.inputs.YEAR }}" ]; then
            python ingest_monthly_to_sqlite.py --year "${{ github.event.inputs.YEAR }}"
          else
            python ingest_monthly_to_sqlite.py --start "${{ github.event.inputs.START }}" --end "${{ github.event.inputs.END }}"
          fi
