name: Ingest Monthly Accounts → yearly_sqlites

on:
  workflow_dispatch:
    inputs:
      START:
        description: "Start month (YYYY-MM), e.g., 2023-01"
        required: true
        default: "2023-01"
      END:
        description: "End month (YYYY-MM), e.g., 2025-06"
        required: true
        default: "2025-06"

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0   # important for pull/rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas httpx stream-read-xbrl

      # Pull before we start so we base work on latest main
      - name: Pull latest to avoid non-fast-forward (pre-commit)
        run: |
          git fetch origin ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }} || true

      - name: Run monthly ingest
        run: |
          python ingest_monthly_to_sqlite.py --start "${{ github.event.inputs.START }}" --end "${{ github.event.inputs.END }}"

      - name: Git LFS install (runner)
        run: git lfs install --local

      - name: Ensure LFS tracking for SQLite
        run: |
          if [ ! -f .gitattributes ] || ! grep -q '\*\.sqlite filter=lfs diff=lfs merge=lfs -text' .gitattributes; then
            git lfs track "*.sqlite"
            echo "Tracked *.sqlite via LFS"
          fi
          git add .gitattributes

      - name: Stage + commit
        run: |
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Ingest monthly CH accounts (${{ github.event.inputs.START }}..${{ github.event.inputs.END }})" || echo "No changes"

      - name: Final rebase, then push (LFS-aware)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git pull --rebase origin ${{ github.ref_name }} || true
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
