name: Ingest Monthly Accounts → yearly_sqlites

on:
  workflow_dispatch:
    inputs:
      START:
        description: "Start month (YYYY-MM), e.g., 2023-01"
        required: true
        default: "2023-01"
      END:
        description: "End month (YYYY-MM), e.g., 2025-06"
        required: true
        default: "2025-06"

permissions:
  contents: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install pandas httpx stream-read-xbrl
      - name: Run monthly ingest
        run: |
          python ingest_monthly_to_sqlite.py --start "${{ github.event.inputs.START }}" --end "${{ github.event.inputs.END }}"
      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Ingest monthly CH accounts (${{ github.event.inputs.START }}..${{ github.event.inputs.END }})" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
