name: Split Large Yearly SQLite

on:
  workflow_dispatch:
    inputs:
      YEAR:
        description: "Year to split (e.g. 2023)"
        required: true

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install pandas

      - name: Run split script
        run: python split_year_sqlite.py --input yearly_sqlites/${{ github.event.inputs.YEAR }}.sqlite

      - name: Commit & push new halves
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add yearly_sqlites/${{ github.event.inputs.YEAR }}_H1.sqlite
          git add yearly_sqlites/${{ github.event.inputs.YEAR }}_H2.sqlite
          git commit -m "Split ${{ github.event.inputs.YEAR }} into half-year SQLite files"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
