name: Daily Company Metadata Sync → Azure

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      CH_API_KEY:         ${{ secrets.CH_API_KEY }}
      AZURE_SQL_SERVER:   ${{ secrets.AZURE_SQL_SERVER }}
      AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
      AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
      AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
      CONCURRENCY: "8"
      TIMEOUT: "20"
      SINCE_DAYS: "30"
      MAX_PER_RUN: "50000"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: ODBC + deps
        run: |
          sudo su -c 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
          sudo su -c 'curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list'
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run metadata sync
        run: python sync_company_metadata.py
