name: Bulk Yearly Company Metadata Sync → Azure

on:
  workflow_dispatch:
    inputs:
      MAX_PER_RUN:
        description: "Max rows this run (blank = unlimited)"
        required: false
        default: ""
      SINCE_DAYS:
        description: "Refresh rows older than N days"
        required: false
        default: ""
      FORCE_REFETCH:
        description: "Set 1 to refetch all"
        required: false
        default: "0"

permissions:
  id-token: write     # needed for OIDC
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 720
    env:
      CH_API_KEY:         ${{ secrets.CH_API_KEY }}

      # Azure SQL creds (SQL authentication)
      AZURE_SQL_SERVER:   ${{ secrets.AZURE_SQL_SERVER }}        # e.g. ixbrl-sql-server.database.windows.net
      AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
      AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
      AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}

      # knobs for fetch_company_metadata
      CONCURRENCY: "8"
      TIMEOUT: "20"
      MAX_PER_RUN:  ${{ github.event.inputs.MAX_PER_RUN }}
      SINCE_DAYS:   ${{ github.event.inputs.SINCE_DAYS }}
      FORCE_REFETCH:  ${{ github.event.inputs.FORCE_REFETCH }}

      # for firewall open/close
      AZ_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZ_RG:           ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZ_SQL_NAME:     ${{ secrets.AZURE_SQL_SERVER_NAME }}   # short server name, e.g. ixbrl-sql-server

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # OIDC login
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Add temp firewall rule
      - name: Allow runner IP in Azure SQL firewall
        run: |
          set -e
          az account set --subscription "$AZ_SUBSCRIPTION"
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "Runner public IP: $RUNNER_IP"
          RULE_NAME="gha-${{ github.run_id }}"
          az sql server firewall-rule create \
            --resource-group "$AZ_RG" \
            --server "$AZ_SQL_NAME" \
            --name "$RULE_NAME" \
            --start-ip-address "$RUNNER_IP" \
            --end-ip-address "$RUNNER_IP"
          echo "FW_RULE_NAME=$RULE_NAME" >> $GITHUB_ENV

      - name: ODBC + deps
        run: |
          sudo su -c 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
          sudo su -c 'curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list'
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install aiohttp pandas sqlalchemy pyodbc httpx stream-read-xbrl
          python -c "import pyodbc; print('Available ODBC drivers:', pyodbc.drivers())"

      - name: Connectivity check
        run: |
          python - <<'PY'
          import os, pyodbc
          cs = ("Driver=ODBC Driver 18 for SQL Server;"
                f"Server=tcp:{os.getenv('AZURE_SQL_SERVER')},1433;"
                f"Database={os.getenv('AZURE_SQL_DATABASE')};"
                f"Uid={os.getenv('AZURE_SQL_USERNAME')};"
                f"Pwd={os.getenv('AZURE_SQL_PASSWORD')};"
                "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=60;")
          print("Attempting test connection…")
          with pyodbc.connect(cs) as conn:
              cur = conn.cursor(); cur.execute("SELECT 1"); print("SELECT 1 ->", cur.fetchone()[0])
          print("Connectivity OK")
          PY

      - name: Run bulk metadata sync
        run: python sync_yearly_company_metadata.py

      - name: Remove runner IP from firewall
        if: always()
        run: |
          az account set --subscription "$AZ_SUBSCRIPTION" || true
          az sql server firewall-rule delete \
            --resource-group "$AZ_RG" \
            --server "$AZ_SQL_NAME" \
            --name "$FW_RULE_NAME" \
            --yes || true
