permissions:
  contents: write

name: Daily iXBRL Sync

on:
  schedule:
    - cron: '0 7 * * *'  # every day at 07:00 UTC
  workflow_dispatch:  # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas httpx stream-read-xbrl

      - name: Run sync script
        run: python sync_latest_ixbrl.py

      - name: Commit and push updated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update latest iXBRL data" || echo "No changes to commit"
          push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/elerk1505/ixbrl-financials-db.git HEAD:main
