name: Daily Company Metadata Sync
permissions:
  contents: write

on:
  schedule:
    - cron: "15 1 * * *"   # Daily at 01:15 UTC (02:15 during BST)
  workflow_dispatch: {}

jobs:
  sync-meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas aiohttp

      - name: Build company_numbers.csv from yearly_sqlites
        run: |
          python scripts/update_company_numbers.py --inputs yearly_sqlites --output data/company_numbers.csv

      - name: Fetch metadata into SQLite
        env:
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
        run: |
          python scripts/fetch_company_metadata.py \
            --api-key "$CH_API_KEY" \
            --csv data/company_numbers.csv \
            --db data/company_metadata.sqlite \
            --concurrency 8 \
            --timeout 20 \
            --since-days 30

      - name: Git LFS install (runner)
        run: git lfs install --local

      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add -A
          git commit -m "Auto-update company metadata" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
