# .github/workflows/sync-metadata.yml
name: Daily Company Metadata Sync

on:
  schedule:
    - cron: "15 1 * * *"   # Daily at 01:15 UTC (02:15 London during BST)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync-metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    concurrency:
      group: sync-metadata
      cancel-in-progress: false

    # Env at the job level applies to all steps
    env:
      COMPANIES_HOUSE_API_KEY: ${{ secrets.CH_API_KEY }}
      TARGET_RPS: "2.0"
      MAX_REQUESTS_PER_RUN: "9000"
      REQUEST_TIMEOUT: "20"
      BATCH_FLUSH: "200"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install httpx pandas

      - name: Run metadata sync
        run: python sync_company_metadata.py

     - name: Commit and push updates
      run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"

      # Safely rebase on latest remote even if local files changed
      git pull --rebase --autostash || true
  
      git add -A
      git commit -m "Auto-update company metadata" || echo "No changes to commit"
      git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
