permissions:
  contents: write

name: Daily iXBRL Sync

on:
  schedule:
    - cron: '0 7 * * *'  # every day at 07:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas httpx stream-read-xbrl

      - name: Ensure output folder exists
        run: mkdir -p yearly_sqlites

      - name: Run sync script
        run: python sync_latest_ixbrl.py

      - name: Git LFS install (runner)
        run: git lfs install --local

      - name: Commit and push updated files (LFS)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add -A
          git commit -m "Auto-update latest iXBRL data (SQLite per year)" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
