name: Daily Company Metadata Sync (no CSV)

on:
  schedule:
    - cron: "0 5 * * *"      # 05:00 UTC daily
  workflow_dispatch:
    inputs:
      MAX_PER_RUN:
        description: "Max companies to fetch this run (blank = unlimited)"
        required: false
        default: "50000"
      SINCE_DAYS:
        description: "Refresh rows older than N days (blank = only missing)"
        required: false
        default: "30"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Ensure LFS blobs present (yearly_sqlites)
        run: |
          git lfs install
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Prepare metadata DB path
        run: |
          mkdir -p data
          if [ -f data/company_metadata.sqlite ]; then
            python - << 'PY'
import sqlite3, os
try:
    con = sqlite3.connect("data/company_metadata.sqlite")
    con.execute("PRAGMA user_version;").fetchall()
    con.close()
    print("metadata DB looks valid")
except Exception as e:
    print("metadata DB invalid, deleting:", e)
    os.remove("data/company_metadata.sqlite")
PY
          fi

      - name: Run daily metadata sync (scan yearly_sqlites directly)
        env:
          CH_API_KEY: ${{ secrets.CH_API_KEY }}
          MAX_PER_RUN: ${{ github.event.inputs.MAX_PER_RUN }}
          SINCE_DAYS: ${{ github.event.inputs.SINCE_DAYS }}
        run: |
          EXTRA_FLAGS=""
          [ -n "$MAX_PER_RUN" ] && EXTRA_FLAGS="$EXTRA_FLAGS --max-per-run $MAX_PER_RUN"
          [ -n "$SINCE_DAYS" ] && EXTRA_FLAGS="$EXTRA_FLAGS --since-days $SINCE_DAYS"

          python sync_yearly_company_metadata.py \
            --input-dir yearly_sqlites \
            --table financials \
            --db data/company_metadata.sqlite \
            $EXTRA_FLAGS

      - name: Pull then push (LFS-aware)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin ${{ github.ref_name }}
          git pull --rebase origin ${{ github.ref_name }} || true
          git add data/company_metadata.sqlite
          git commit -m "Daily company metadata sync (no CSV)" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
