name: Daily Company Metadata Sync

on:
  schedule:
    - cron: "15 1 * * *"   # Daily at 01:15 UTC (02:15 during BST)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync-metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    concurrency:
      group: sync-metadata
      cancel-in-progress: false

    env:
      # Required
      CH_API_KEY: ${{ secrets.CH_API_KEY }}

      # Where your input CSVs live (space-separated folders)
      # e.g. "financials_2022 financials_2023 daily_drops"
      INPUT_DIRS: "financials"

      # Output artifacts
      COMPANY_NUMBERS_CSV: "data/company_numbers.csv"
      METADATA_DB: "data/company_metadata.sqlite"

      # Fetcher controls (tune as desired)
      CONCURRENCY: "8"
      TIMEOUT: "20"
      # Optionally refresh rows older than N days
      REFRESH_SINCE_DAYS: "30"
      # Set to "1" to refetch everything regardless of cache
      FORCE_REFETCH: "0"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run sync (orchestrates update + fetch)
        run: python sync_company_metadata.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase --autostash || true
          git add -A
          git commit -m "Auto-update company metadata" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
