# .github/workflows/sync-metadata.yml
name: Daily Company Metadata Sync

on:
  schedule:
    # Daily at 01:15 UTC (02:15 London during BST)
    - cron: "15 1 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync-metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    concurrency:
      group: sync-metadata
      cancel-in-progress: false

    env:
      # Map your existing secret name to what the script expects
      COMPANIES_HOUSE_API_KEY: ${{ secrets.CH_API_KEY }}
      TARGET_RPS: "2.0"              # ~2 req/sec to stay under CH pacing
      MAX_REQUESTS_PER_RUN: "9000"   # chew through backlog daily
      REQUEST_TIMEOUT: "20"
      BATCH_FLUSH: "200"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install httpx

      - name: Run metadata sync
        run: python sync_company_metadata.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add company_metadata.csv sync_metadata.progress.json || true
          git commit -m "Auto-update company metadata" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
