name: Weekly Company Metadata Sync

on:
  schedule:
    - cron: '0 5 * * 1'  # every Monday at 05:00 UTC
  workflow_dispatch:  # allow manual run

permissions:
  contents: write

jobs:
  sync-metadata:
    runs-on: ubuntu-latest
    env:
      CH_API_KEY: ${{ secrets.CH_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas httpx

      - name: Run metadata sync
        run: python sync_company_metadata.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add company_metadata.csv
          git commit -m "Auto-update company metadata" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
